/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}
#paso 1
fun main() {
    println("hola kotlin")
    yo()
    
}
fun yo() {
    val nombre: String = "Santi valla"
    val edad: Int = 16
    println("$nombre, $edad")
}