/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
//paso 1
fun main() {
    println("hola kotlin")
    val numero: Int = 5
    yo() 
    datos()
    area()
    println(esParOImpar(numero))
    println(posnego0(numero))
    loops1()
    loops2()
}
fun yo() {
    val nombre: String = "Santi valla"
    val edad: Int = 16
    println("$nombre, $edad")
}
//paso 2
fun datos() {
    val string: String = "hola"
    val entero: Int = 912
    val double: Double = 1.5
    val booleano: Boolean = true
    println("String: $string, entero: $entero, double: $double, booleano: $booleano")
}
fun area() {
    val base: Int = 10
    val altura: Int = 5
    val area: Int = base * altura
    println("El área del rectángulo es: $area")
}
//paso 3
fun esParOImpar(numero: Int): String {
    return if (numero % 2 == 0) {
        "$numero es par"
    } else {
        "$numero es impar"
    }
}
fun posnego0(numero: Int): String {
    return if (numero > 0) {
        "$numero es positivo"
    } else if (numero < 0) {
       "$numero es negativo"
    } else {
        "$numero es cero"
    }  
}
//paso 4
fun loops1() {
    for (i in 1..10) {
        println("metodo for: $i")
    }
    var j: Int= 1
    while (j<=10) {
        println("metodo while: $j")
        j++
    }
    var k: Int= 1
    do {
        println("metodo do while: $k")
        k++
    } while (k<=10)
}
fun loops2() {
    for (l in 1..10 step 2) {
        println("metodo for: $i")
    }
    var m: Int= 2
    while (m<=20) {
        println("metodo while: $j")
        m++2
    }
    var n: Int= 2
    do {
        println("metodo do while: $k")
        n++2
    } while (n<=20)
}